AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        name:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~